services:
  fullstack:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "uvicorn main:app --reload 0.0.0.0 --port 8000 & cd frontend && npm start & wait"